info:
  artifactId: '${project.name}'
  version: '${project.version}'

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: test
    listener:
      type: simple
      simple:
        prefetch: 1
        concurrency: 2
        max-concurrency: 10
  datasource:
    url: jdbc:mysql://localhost:3306/rabbit?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=UTC
    username: root
    password: 'root'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none